FROM node:8.11.2-stretch

ADD https://github.com/progrium/entrykit/releases/download/v0.4.0/entrykit_0.4.0_Linux_x86_64.tgz /entrykit.tgz

RUN tar xf /entrykit.tgz \
    && rm /entrykit.tgz \
    && mv ./entrykit /bin/entrykit \
    && chmod +x /bin/entrykit \
    && /bin/entrykit --symlink

ADD https://github.com/yarnpkg/yarn/releases/download/v1.7.0/yarn-v1.7.0.tar.gz /opt/yarn.tgz

RUN cd /opt \
    && tar xf yarn.tgz \
    && ln -s yarn-1.7.0/bin/yarn /bin/yarn

WORKDIR /code

ENTRYPOINT ["prehook", "node -v", "--", \
            "prehook", "yarn install --modules-folder /node_modules", "--", \
            "yarn", "run", "start", "-n"]
