[build]
  publish = "build"
  command = "yarn build"

[context.production.environment]
  REACT_APP_API_SERVER = "https://api.sakuten.jp"

[context.deploy-preview.environment]
  REACT_APP_API_SERVER = "https://sakuten-api-testflight.herokuapp.com"
  REACT_APP_STAGING_BUILD = "1"

[context.branch-deploy.environment]
  REACT_APP_API_SERVER = "https://api.sakuten.jp"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/index.html"
  [headers.values]
    Content-Security-Policy = "default-src 'self' https:; font-src 'self' https: data:; img-src 'self' https: data:; object-src 'none'; worker-src blob:; script-src blob: https:; style-src 'self' https: 'unsafe-inline'"
    Strict-Transport-Security = "max-age=631138519"
    X-Content-Type-Options = "nosniff"
    X-Download-Options = "noopen"
    X-Frame-Options = "sameorigin"
    X-Permitted-Cross-Domain-Policies = "none"
    X-Xss-Protection = "1; mode=block"
